version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "@astrojs/language-server"
      - dependency-name: "@astrojs/ts-plugin"
      - dependency-name: "prettier-plugin-astro"
